services:
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama-warehouse-gpu
    #pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  frontend:
    image: slabstech/warehouse-ui
    container_name: frontend-gpu
    ports:
      - 8000:8000  # Map the container port to the host
    depends_on:
      - ollama  # Ensure that the ollama service is started before the frontend service
    extra_hosts:
      - host.docker.internal:host-gateway