services:
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama-warehouse-gpu
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]