services:
  vllm:
    image: ghcr.io/mistralai/mistral-src/vllm:latest
    runtime: nvidia
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HF_TOKEN=${HF_TOKEN}
    command: 
      - --host
      - 0.0.0.0
      - --model
      - mistralai/Mistral-7B-Instruct-v0.2
      - --gpu-memory-utilization
      - "0.95"
      - --max-model-len
      - "8192"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"] #count: all
              capabilities: [gpu]
    ipc: host
