services:
  vllm:
    image: vllm/vllm-openai:latest
    runtime: nvidia
    shm_size: 1g
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HF_TOKEN}
    command:
      - --model
      - mistralai/Mistral-7B-v0.3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
